# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        PSB\AdminBundle\Entity\User: bcrypt

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_USER, ROLE_REP]
        ROLE_REP:         [ROLE_USER]
        ROLE_USER:        []

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_providers:
            chain:
                providers:  [user_db]
        user_db:
            entity: { class: PSBAdminBundle:User, property: username }

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        admin:
            pattern: /admin/.*
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: /admin
            logout:
                path: admin_logout
                target: /
            security: true
            anonymous: true
            remember_me:
                key:        "%secret%"
                lifetime:   86400
                path:       /
                domain:     ~

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options

    # NOTE TO SELF: Top->down priority!
    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/.*, roles: ROLE_USER }
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY } 